#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#Licensed by Alan Laughter under the GPL v3

#3rd party imports
import web
from pprint import pprint

#built-in imports
import sys
import os
import time
import re
import json
import uuid

#personal imports
from utilities import dbmkr, login
from utilities.data import chomp, is_number, zero_out, log
from defpages import admin_login, admin_panel, admin_post

config_lines = open(os.path.join("config","sites_available"),"r"
    ).read().strip("\r").split("\n")

"""
          
databases--domain--pages--cookiename--GET--infodict
                  \                  \
                   \                   POST--infodict
                    \                      \
                     \                       inputs
                      \
                        users--username--permissions
                             \
                               password

databases{'laughware.org':{'pages':{'pagename':},'login':{}}}
"""





























